##===- examples/HowToUseJIT/Makefile -----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by Valery A. Khamenya and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..
TOOLNAME = Prototype

LINK_COMPONENTS := jit interpreter native bitreader

include $(LEVEL)/Makefile.common
